
development:
  adapter: postgresql
  encoding: utf8
  database: data_import_development
  username: <%= `whoami`.strip %>
  host: localhost
  min_messages: warning

test:
  adapter: postgresql
  encoding: utf8
  database: data_import_test
  username: <%= `whoami`.strip %>
  min_messages: warning

